### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by maartenberg** [spasticVerbalizer/SchetsEnScheef#1]
- [x] Artistieker verantwoorde icoontjes voor ellips en vollips, vollips hernoemen naar iets anders?
- [x] Het nieuwe gummen:
  - [x] Nieuwe klassen: PuntVorm en kinders, hebben methodes voor tekenen en bepalen of ze geklikt zijn
    - [x] PuntVorm
      - [x] TekstVorm
    - [x] TweePuntVorm
      - [x] LijnVorm
      - [x] RechthoekVorm (gevuld)
        - [x] KaderVorm
          - [x] EllipsVorm (misschien omwerken naar dat ie een kind van TweePuntVorm ipv Kader is)
            - [x] VollipsVorm
  - [x] Tools maken Vormen ipv op de bitmap tekenen
    - [x] PuntVorm
      - [x] TekstVorm (TODO verzamelingnummer)
    - [x] TweePuntVorm
      - [x] LijnVorm
      - [x] RechthoekVorm (gevuld)
        - [x] KaderVorm
          - [x] EllipsVorm (misschien omwerken naar dat ie een kind van TweePuntVorm ipv Kader is)
            - [x] VollipsVorm
  - [x] Schets heeft een List<PuntVorm> om alles bij te houden en zichzelf te tekenen
  - [x] Pen-lijnen hebben een VerzamelingNummer om met de gum in één keer de hele lijn te deleten, zijn wel aparte elementen
  - [x] Teksten kunnen evt. nog ook aan het VerzamelingNummer-zooi inhaken (protected int in TekstTool, bij iedere muisklik omhoog
    - [x] TekstTool kan evt. spaties krijgen (vaste hoeveelheid opschuiven)
  - [x] Gum omgezet naar dat elementen uit de vormenlijst worden gegooid
- [x] Het nieuwe opslaan en teruglezen
  - [x] Vormen moeten een methode krijgen om alle parameters in een string te dumpen -> dit wordt ToString
  - [x] Vormen moeten een soort tweede constructor krijgen die een array van strings accepteerd en daar weer een vorm uit opbouwt
  - [x] Een schets moet een methode krijgen om alle elementen in een file te dumpen
  - [x] Een schets moet een methode krijgen om alle elementen uit een file te lezen
- [ ] Extra's:
  - [x] Undo-knop: Trap het bovenste element (index [Vormen.Count-1]) uit de lijst, evt. op een stack opslaan voor Redo, stack eruit gooien zodra er weer wordt getekend.
  - [ ] Lijndikte variabel maken (en dus ook als parameter aan alle dingen die een lijn gebruiken geven en laten opslaan en inlezen)
  - [ ] Tool om dingen bovenop (verplaatsen naar index [Vormen.Count-1]) of onderop (verplaatsen naar index 1 (0 is achtergrond)) te plaatsen
  - [ ] Tool om dingen te draggen naar een andere plaats
  - [ ] Elementen resizen met window-resize (??? dit is wss niet leuk)
  - [ ] Zelf zinvolle uitbreidingen verzinnen:
    - [x] Paintbucket
    - [x] Regenboog/iets-pen?  
      ![Voorbeeld](http://onlinehelp.smarttech.com/english/windows/help/notebook/10_8_0/Content/Resources/Images/ExampleCreativePen.png)
    - [ ] ~~Achtergrondmuziek~~
    - [ ] ???
- [ ] Pre-inlever opruiming:
  - [ ] Oude weggecommentaarde code verwijderen
  - [ ] Nuttig commentaar bij de nieuwe functies schrijven
  - [ ] Document met uitleg
  - [ ](Diff van verschillen met startversie voor pret en plezier maken)
